# Generated by Django 5.2 on 2025-04-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_cita_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Normativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo_combustible', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diésel', 'Diésel'), ('Eléctrico', 'Eléctrico'), ('Híbrido', 'Híbrido')], max_length=20)),
                ('limite_co', models.DecimalField(decimal_places=2, max_digits=5)),
                ('limite_nox', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usa_obd', models.BooleanField()),
                ('frecuencia_meses', models.PositiveIntegerField()),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
