# Generated by Django 5.2 on 2025-04-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_vehiculo_verificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='co_medido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='nox_medido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
