# Generated by Django 5.2 on 2025-04-28 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_vehiculo_co_medido_vehiculo_nox_medido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('motivo', models.TextField()),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.vehiculo')),
                ('verificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.verificacion')),
            ],
        ),
    ]
